#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use NodesAndEdges\Command\StrongComponentsCommand;
use NodesAndEdges\Command\TopologicalOrderCommand;
use Symfony\Component\Console\Application;
use NodesAndEdges\Command\PrintGraphCommand;
use NodesAndEdges\Command\GraphInfoCommand;
use NodesAndEdges\Command\DFSCommand;
use NodesAndEdges\Command\DFSPathCommand;
use NodesAndEdges\Command\BFSPathCommand;

$application = new Application();

$application->add(new PrintGraphCommand());
$application->add(new GraphInfoCommand());
$application->add(new DFSCommand());
$application->add(new DFSPathCommand());
$application->add(new BFSPathCommand());
$application->add(new TopologicalOrderCommand());
$application->add(new StrongComponentsCommand());
$application->run();

